Adding ArcAssay Sheets api
nfdi4plants/ISADotNet pull request #116
Opened 2023-06-22 10:11 UTC by Freymaurer

- Changed `ArcAssay.Sheets` from `ArcTable list option` to `ResizeArray<ArcTable>` to support mutability.
- Maybe rename `Sheets` to `Tables` ?
- Hit >300 unit tests 🎉 ✅ 
- JS tests not yet run ❌

2023-06-23 14:09 UTC, Freymaurer commented
@HLWeil please have a look!

2023-06-26 08:36 UTC, HLWeil requested changes
<3

2023-06-26 08:36 UTC, HLWeil commented on src/ISA/ISA/ArcTypes/ArcAssay.fs
> +    let getNextAutoGeneratedTableName (existingNames: seq<string>) =
I would enforce users to set table names themselves when using this API.

2023-06-26 08:36 UTC, HLWeil commented on src/ISA/ISA/ArcTypes/ArcTable.fs
> +    override this.GetHashCode () = this.GetHashCode()
rip

2023-06-26 08:36 UTC, HLWeil commented on src/ISA/ISA/ArcTypes/ArcAssay.fs
> +    member this.AddTable(?table:ArcTable, ?index: int) =
```fsharp
member this.AddTable(table:ArcTable, ?index: int) : unit

member this.InitTable(tableName : string, ?index : int) : ArcTable
```

2023-06-26 08:36 UTC, HLWeil commented on src/ISA/ISA/ArcTypes/ArcAssay.fs
> +    member this.AddTable(?table:ArcTable, ?index: int) =
Maybe something like this?

2023-06-26 08:36 UTC, HLWeil commented on src/ISA/ISA/ArcTypes/ArcAssay.fs
> +        tryByTableName name this.Tables
rename

2023-06-26 08:36 UTC, HLWeil commented on src/ISA/ISA/ArcTypes/ArcAssay.fs
> +            newAssay.GetTableAt(index)
- add comment to make clear that the user receives a copied object
- copy table, not assay

2023-06-30 13:42 UTC, Freymaurer commented
Renamed "Set" CRUD api functions to "Updated"; `SetColumn` --> `UpdateColumn`
Renamed `UpdateTableAt` functions on ArcAssay and ArcStudy to `MapTableAt`

```fsharp
member this.MapTableAt(index: int, updateFun: ArcTable -> unit) = ArcTables(this.Tables).MapTableAt(index, updateFun)
```

2023-07-02 11:01 UTC, HLWeil commented
Great work! 

I will merge this, so I can start using these functions in the FsSpreadsheet IO. If we decide on additional changes feel free to open up a new PR.

2023-07-02 11:01 UTC, merged